logging_system/config/urls.py
from django.urls import path

from . import views

app_name = "config"

urlpatterns = [
    path("", views.settings, name="settings"),
    path("reset", views.reset, name="reset"),
    path("reset/ml", views.reset_ml, name="reset_ml"),
]

logging_system/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health_check, name="health_check"),
    path("", views.home, name="home"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
]

logging_system/incidents/urls.py
from django.urls import path

from . import views

app_name = "incidents"

urlpatterns = [
    path("", views.incidents, name="list"),
    path("<int:tag>", views.incidents, name="list"),
    path("view/<int:pk>", views.view, name="view"),
    path("resolve/<int:pk>", views.resolve, name="resolve"),
    path("remove/<int:pk>", views.remove, name="remove"),
    path("report/<int:frame>", views.report, name="report"),
    path("report/<int:frame>/<int:tag>", views.report, name="report"),
    #    path('path/', views.view, name='name'),
]

logging_system/logs/urls.py
from django.urls import path

from . import views

app_name = "logs"

urlpatterns = [
    path("", views.logs, name="list"),
    path("<int:label>", views.logs, name="list"),
    path("export", views.export, name="export"),
    path("export/<int:pk>", views.export, name="export"),
]

logging_system/systems/urls.py
from django.urls import path

from . import views

app_name = "systems"

urlpatterns = [
    path("", views.systems, name="list"),
    path("location/<int:location>", views.systems, name="location"),
    path("type/<int:system_type>", views.systems, name="list"),
    path("view/<int:pk>", views.system, name="view"),
    path("logs/<int:pk>", views.logs, name="logs"),
    path("logs/<int:pk>/<int:label>", views.logs, name="logs"),
    path("incidents/<int:pk>", views.incidents, name="incidents"),
    path("incidents/<int:pk>/<int:tag>", views.tag_incidents, name="tag"),
    path("add/", views.add, name="add"),
    path("discover/", views.discover, name="discover"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("remove/<int:pk>", views.remove, name="remove"),
    path("export", views.export_to_csv, name="export"),
    path("export/<int:system_type>", views.export_to_csv, name="export"),
    path("report", views.report, name="report"),
    path("report/<int:system_type>", views.report, name="report"),
]

logging_system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("logging_system.home.urls")),
    path("settings/", include("logging_system.config.urls")),
    path("logs/", include("logging_system.logs.urls")),
    path("systems/", include("logging_system.systems.urls")),
    path("incidents/", include("logging_system.incidents.urls")),
    path("locations/", include("logging_system.locations.urls")),
    path("audit_log/", include("logging_system.audit_log.urls")),
    # path('incidents/', include('incidents.urls')),
]

logging_system/incidents/models.py
from django.contrib.auth.models import User
from django.db import models

from logging_system.systems.models import System

# Create your models here.

TAG_CHOICES = [
    (0, "System down"),
    (1, "Log anomaly"),
]


class Incident(models.Model):
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    system = models.ForeignKey(System, on_delete=models.CASCADE, null=True)
    ip = models.CharField(max_length=50)
    tag = models.IntegerField(choices=TAG_CHOICES, default=0)
    title = models.CharField(max_length=255)
    message = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, default=None)

    def save(self, *args, **kwargs):
        if self.ip:
            self.ip = self.ip[:50]
        if self.title:
            self.title = self.title[:255]
        if self.message:
            self.message = self.message[:255]
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        if self.message:
            self.message = self.message[:255]
        super().save(*args, **kwargs)

    def __str__(self):
        return self.message

logging_system/audit_log/views.py
from datetime import timedelta

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone

from logging_system.config.models import Settings
from logging_system.functions import pagination

from .models import AuditLog


# Create your views here.
@staff_member_required(login_url="/accounts/login/")
def logs(request, user=None):
    audit_logs = None
    q = request.GET.get("search", "")
    if user is not None:
        # Fix to display system audit logs
        if user == 0:
            user = None
        if q:
            audit_logs = AuditLog.objects.filter(
                Q(message__icontains=q) | Q(user__username__icontains=q), user=user
            ).order_by("-id")
        else:
            audit_logs = AuditLog.objects.filter(user=user).order_by("-id")
    else:
        if q:
            audit_logs = AuditLog.objects.filter(
                Q(message__icontains=q) | Q(user__username__icontains=q)
            ).order_by("-id")
        else:
            audit_logs = AuditLog.objects.order_by("-id")
    page = pagination(audit_logs, request.GET.get("page"))
    users = User.objects.all()
    data = {"audit_logs": page, "users": users}
    return render(request, "audit_log/list.html", data)


@staff_member_required(login_url="/accounts/login/")
def report(request, frame=0, user=None):
    AuditLog.objects.create(
        user=request.user, message=f"User {request.user} created audit logs report."
    )

    start = (
        timezone.now() - timedelta(weeks=9999)
        if frame == 0
        else timezone.now() - timedelta(days=30)
        if frame == 1
        else timezone.now() - timedelta(days=7)
    )

    audit_log = (
        AuditLog.objects.filter(datetime__gte=start, user__isnull=True)
        .order_by("id")
        .order_by("-id")[:5000]
        if user == 0
        else AuditLog.objects.filter(datetime__gte=start).order_by("-id")[:5000]
        if user is None
        else AuditLog.objects.filter(datetime__gte=start, user=user)
        .order_by("id")
        .order_by("-id")[:5000]
    )

    current_date = timezone.now()
    return render(
        request,
        "report/audit_log.html",
        {
            "date": current_date,
            "start": start,
            "audit_logs": audit_log,
            "user": request.user,
        },
    )

logging_system/config/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect, render

from logging_system.audit_log.models import AuditLog

from .forms import SettingsPage
from .models import Settings


# Create your views here.
@staff_member_required(login_url="/accounts/login/")
def settings(request):
    settings = Settings.load()
    form = SettingsPage(request.POST or None, instance=settings)
    if form.is_valid():
        form.save()
        AuditLog.objects.create(
            user=request.user, message=f"User {request.user} updated settings."
        )
        messages.success(request, "Settings updated successfully")
        return redirect("home")
    else:
        return render(request, "misc/settings.html", {"form": form})


@staff_member_required(login_url="/accounts/login/")
def reset(request):
    settings = Settings.load()
    settings.delete()

    AuditLog.objects.create(
        user=request.user,
        message=f"User {request.user} restored default configuration.",
    )
    messages.success(request, "Configuration restored")
    return redirect("config:settings")


@staff_member_required(login_url="/accounts/login/")
def reset_ml(request):
    settings = Settings.load()

    settings.s1_vectorizer = 1
    settings.s1_vectorizer_parameters = None
    settings.s1_clusterer = 1
    settings.s1_clusterer_parameters = None
    settings.s2_vectorizer = 0
    settings.s2_vectorizer_parameters = None
    settings.s2_clusterer = 3
    settings.s2_clusterer_parameters = None
    settings.on_model_change_reset = False
    settings.ml_anomaly_cluster = 0
    settings.ml_train = 2000
    settings.ml_train_interval = 3
    settings.ml_cluster = 10000
    settings.ml_cluster_interval = 3

    settings.save()
    AuditLog.objects.create(
        user=request.user,
        message=f"User {request.user} restored default ml configuration.",
    )
    messages.success(request, "ML configuration restored")
    return redirect("config:settings")

logging_system/devices/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from website.functions import get_ping_graph
from .models import Device, Log
from config.models import Settings
from .forms import DeviceForm
# Create your views here.

def devices(request):
    if request.user.is_authenticated:
        devices = Device.objects.all().order_by("id")

        # update device last_log
        for device in devices:
            device.graph = get_ping_graph(device.ip)
            last_log = Log.objects.filter(host= device.ip).last()
            if last_log is not None:
                device.last_log = last_log.datetime
                device.save()

        paginator = Paginator(devices, 10)
        page_number = request.GET.get("page")
        page_devices = paginator.get_page(page_number)
        
        return render(request, 'devices.html', {'devices': page_devices})
    else:
        return redirect('home')

def logs(request, pk):
    if request.user.is_authenticated:

        host = Device.objects.get(id=pk)

        label = request.GET.get('label')
        if label is not None:
            logs = Log.objects.filter(host= host.ip, label=label)
        else:
            logs = Log.objects.filter(host= host.ip)
   
        sort_by = request.GET.get('sort')
        if sort_by in ['datetime', 'host', 'program', 'message']:
            logs = logs.order_by(sort_by)
        else:
            logs = logs.order_by('-id')
            
        items_per_page = Settings.load().items_per_page
        paginator = Paginator(logs, items_per_page)
        page_number = request.GET.get("page")
        page_logs = paginator.get_page(page_number)

        return render(request, 'device_logs.html', {'host': host, 'logs': page_logs, 'label': label, 'sort': sort_by,})
        pass
    else:
        return redirect('home')

def add(request):
    if request.user.is_authenticated:
        form = DeviceForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                add_record = form.save()
                messages.success(request, "Device added successfully")
                return redirect('devices:list')
        else:
            return render(request, 'add_device.html', {'form': form})
        return render(request, 'add_device.html', {'form': form})
    else:
        return redirect('home')

def edit(request, pk):
    if request.user.is_authenticated:
        update_it = Device.objects.get(id=pk)
        form = DeviceForm(request.POST or None, instance=update_it)
        if form.is_valid():
            form.save()
            messages.success(request, "Device updated successfully")
            return redirect('devices:list')
        else:
            return render(request, 'edit_device.html', {'form': form})
    else:
        return redirect('home')

def remove(request, pk):
    if request.user.is_authenticated:
        delete_it = Device.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, "Device removed successfully")
        return redirect('devices:list')
    else:
        return redirect('home')

# validated function

# def function(request):
#     if request.user.is_authenticated:
#         pass
#     else:
#         return redirect('home')

logging_system/home/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import redirect, render
from ping3 import ping
from requests import get

from logging_system.audit_log.models import AuditLog
from logging_system.config.models import Settings
from logging_system.incidents.models import Incident
from logging_system.logs.models import Log
from logging_system.systems.models import System

from .forms import SignUpForm


# docker compose health check
def health_check(request):
    return JsonResponse({"status": "ok"})


# Create your views here.


@login_required
def home(request):
    response = None
    ip = None

    incidents = Incident.objects.all().order_by("-id")[: Settings.load().items_per_page]

    try:
        response = f"{ping('8.8.8.8', unit='ms'):.3} ms"
        ip = get("https://api.ipify.org").content.decode("utf8")
    except:
        response = None
        ip = None

    class Statistics:
        pass

    statistics = Statistics()

    # Incidents
    statistics.incident_count = Incident.objects.count()
    statistics.incident_resolved_count = Incident.objects.filter(
        user__isnull=False
    ).count()

    try:
        statistics.incident_resolved_ratio = round(
            statistics.incident_resolved_count / statistics.incident_count * 100
        )
    except ZeroDivisionError:
        statistics.incident_resolved_ratio = 0

    statistics.incident_tag0_count = Incident.objects.filter(tag=0).count()
    statistics.incident_tag1_count = Incident.objects.filter(tag=1).count()
    statistics.incident_tag0_unresolved_count = Incident.objects.filter(
        tag=0, user__isnull=True
    ).count()
    statistics.incident_tag1_unresolved_count = Incident.objects.filter(
        tag=1, user__isnull=True
    ).count()

    try:
        statistics.incident_tag0_ratio = round(
            statistics.incident_tag0_unresolved_count
            / statistics.incident_tag0_count
            * 100
        )
    except ZeroDivisionError:
        statistics.incident_tag0_ratio = 0

    try:
        statistics.incident_tag1_ratio = round(
            statistics.incident_tag1_unresolved_count
            / statistics.incident_tag1_count
            * 100
        )
    except ZeroDivisionError:
        statistics.incident_tag1_ratio = 0

    # Log
    statistics.log_count = Log.objects.count()
    statistics.log_anomaly_count = Log.objects.filter(label=0).count()

    try:
        statistics.log_anomaly_ratio = round(
            statistics.log_anomaly_count / statistics.log_count * 100
        )
    except ZeroDivisionError:
        statistics.log_anomaly_ratio = 0

    statistics.log_devices_anomaly = (
        Log.objects.filter(label=0)
        .values("host")
        .annotate(count=Count("host"))
        .order_by("-count")
    )

    # Systems
    statistics.system_count = System.objects.count()
    statistics.system_down_count = System.objects.filter(d_count__gt=0).count()

    try:
        statistics.system_down_ratio = round(
            statistics.system_down_count / statistics.system_count * 100
        )
    except ZeroDivisionError:
        statistics.system_down_ratio = 0

    statistics.system_systems_down = System.objects.filter(d_count__gt=0).order_by(
        "d_count"
    )[:3]

    data = {
        "ip": ip,
        "ping": response,
        "incidents": incidents,
        "statistics": statistics,
        # 'logs': logs,
        # 'labels_graph': labels_graph,
        # 'uptime_graph': uptime_graph
    }

    return render(request, "misc/home.html", data)


def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out")
    return redirect("home")


def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(request, username=username, password=password)
            login(request, user)
            AuditLog.objects.create(
                user=user, message=f"{user} created account successfuly."
            )
            messages.success(request, "You have successfuly created an account!")
            return redirect("home")
        pass
    else:
        form = SignUpForm()
        return render(request, "registration/register.html", {"form": form})

    return render(request, "registration/register.html", {"form": form})

logging_system/templates/incident/list.html
{% extends 'elements/base.html' %} {% block content %}
<div class="col-md-12">
    <div class="d-flex justify-content-between">
        <div class="input-group mb-3">
            <a class="btn btn-secondary" href="{{ request.META.HTTP_REFERER|default:'/' }}">&laquo; Back</a>
            <a class="btn btn-outline-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                {% if system %}
                    {{ system }}'s incidents
                {% else %}
                    All incidents
                {% endif %}
            </a>
            <ul class="dropdown-menu" style="max-height: 180px; overflow-y: auto;">
                <li><a class="dropdown-item" href="{% url 'incidents:list' %}">All</a></li>
                {% if systems %}
                {% for obj in systems %}
                    {% if obj.id %}
                    <li><a class="dropdown-item" href="{% url 'systems:incidents' obj.id %}">{{ obj }}</a></li>
                    {% endif %}
                {% endfor %}
                {% endif %}
            </ul>
            <a class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" > Create Report </a>
            <ul class="dropdown-menu" style="max-height: 360px; overflow-y: auto;">
                {% comment %} <li><a href="{% url 'incidents:report' %}"class="dropdown-item">Today</a></li> {% endcomment %}
                <li><a href="{% url 'incidents:report' 0 %}" class="dropdown-item bg-secondary text-bg-dark">All</a></li>
                <li><a href="{% url 'incidents:report' 1 %}"class="dropdown-item">Last Week</a></li>
                <li><a href="{% url 'incidents:report' 2 %}"class="dropdown-item">Last Month</a></li>
                {% comment %} <li><a href="{% url 'incidents:report' %}"class="dropdown-item">Custom</a></li> {% endcomment %}
                <li><a href="{% url 'incidents:report' 0 0 %}" class="dropdown-item bg-secondary text-bg-dark">System down</a></li>
                {% comment %} <li><a href="{% url 'incidents:report_tag' 0 %}" class="dropdown-item">Today</a></li> {% endcomment %}
                <li><a href="{% url 'incidents:report' 1 0 %}" class="dropdown-item">Last Week</a></li>
                <li><a href="{% url 'incidents:report' 2 0 %}" class="dropdown-item">Last Month</a></li>
                {% comment %} <li><a href="{% url 'incidents:report_tag' 0 %}" class="dropdown-item">Custom</a></li> {% endcomment %}
                <li><a href="{% url 'incidents:report' 0 1 %}" class="dropdown-item bg-secondary text-bg-dark">Log anomaly</a></li>
                {% comment %} <li><a href="{% url 'incidents:report_tag' 1 %}" class="dropdown-item">Today</a></li> {% endcomment %}
                <li><a href="{% url 'incidents:report' 1 1 %}" class="dropdown-item">Last Week</a></li>
                <li><a href="{% url 'incidents:report' 2 1 %}" class="dropdown-item">Last Month</a></li>
                {% comment %} <li><a href="{% url 'incidents:report_tag' 1 %}" class="dropdown-item">Custom</a></li> {% endcomment %}
            </ul>
        </div>
        <form method="get" class="align-self-center">
            <div class="input-group">
                <input class="form-control" type="text" name="search" value="{{ q }}" placeholder="Your query">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </form>
    </div>
    <div class="accordion" id="accordionServices">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <div class="accordion-button collapsed">
                    <div class="container text-start">
                        <div class="row">
                            <div class="col-1">ID:</div>
                            <div class="col-2">Date:</div>
                            <div class="col-2">System:</div>
                            <div class="col-2"><a
                                class="nav-link dropdown-toggle"
                                href="#"
                                role="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                                >
                                Tag:
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'incidents:list' %}">All</a></li>
                                    <li><a class="dropdown-item" href="{% url 'incidents:list' 0 %}">System down</a></li>
                                    <li><a class="dropdown-item" href="{% url 'incidents:list' 1 %}">Log anomaly detected</a></li>
                                </ul>
                            </div>
                            <div class="col-4">Title:</div>
                            <div class="col-1">Resolved:</div>
                        </div>
                    </div>
                </div>
            </h2>
        </div>
        {% if incidents %}
        <div style="max-height: 70vh; overflow-y: auto;">
        {% include 'datatables/incidents.html' with incidents=incidents %}
        </div>
    {% endif %}
    </div>
    <br />
    {% include 'elements/pagination.html' with objs=incidents %}
</div>
{% endblock %}

logging_system/templates/incident/view.html
{% extends 'elements/base.html' %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <div class="input-group mb-3">
        <a class="btn btn-secondary" href="{% url 'incidents:list' %}">&laquo; Back</a>
        <a class="btn btn-outline-dark disabled" > Incident {{ incident.id }} </a>
    </div>
    {% if incident %}
    <div class="card">
        <div class="card-body card-header">
            <h5 class="card-title ">Incident #{{incident.id}}</h5>
            <p class="card-text">{{incident.title}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <p><strong>Incident date: </strong>{{incident.date}}</p> 
                <p><strong>Incident time: </strong>{{incident.time}}</p>
                <p><strong>System IP address: </strong>{{incident.system.ip}}</p>
                <p><strong>Incident tag: </strong>{{incident.get_tag_display}}</p>
                {% if incident.user %}
                <p><strong>Resolved by: </strong>{{incident.user.username}}</p>
                {% endif %}
            </li>
            <li class="list-group-item">
                <p><strong>Incident message: </strong>{{incident.message|linebreaksbr}}</p>
            </li>
        </ul>
        <div class="card-footer">
            <div class="input-group mb-3">
                {% if incident.user %}
                {% else %}
                <a class="btn btn-success" href="{% url 'incidents:resolve' incident.id%}"> Resolve <a>
                {% endif %}
                <a class="btn btn-dark" href="{% url 'systems:view' incident.system.id%}"> View System </a>
                <a class="btn btn-danger" href="{% url 'incidents:remove' incident.id %}"> Remove </a>
            </div>
        </div>
    </div>
    <br/>
    <div class="card">
        <div class="card-header">
            Discussion
        </div>
        <ul class="list-group list-group-flush">
            {% if comments %}
            {% for comment in comments %}
            <li class="list-group-item">
                <p>{{ comment.date }} at {{comment.time}} <strong>{{ comment.user.username }}</strong> said:</p>
                <div class="card-footer text-muted">
                    {{ comment.message}}
                </div>
            </li>
            {% endfor %}
            {% else %}
            <li class="list-group-item">
                <p><strong>No comments yet.</strong></p>
            </li>
            {% endif %}
            <li class="list-group-item">
                <form method="POST" >
                    {% csrf_token %} {% if form.errors %}
                    <p>Your comment:</p>
                    {% comment %} {{ form.message.label_tag }} {% endcomment %}
                    <div class="input-group">
                        {{ form.message }}
                        {% endif %}
                        <button type="submit" class="btn btn-dark"> Submit </button>
                    </div>
                </form>
            </li>
        </ul>
    </div>
    {% else %}
    <h2> Error 404, incident not found </h2>
    {% endif %}
</div>
<br/>
{% endblock %}