logging_system/config/urls.py
from django.urls import path

from . import views

app_name = "config"

urlpatterns = [
    path("", views.settings, name="settings"),
    path("reset", views.reset, name="reset"),
    path("reset/ml", views.reset_ml, name="reset_ml"),
]

logging_system/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health_check, name="health_check"),
    path("", views.home, name="home"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
]

logging_system/incidents/urls.py
from django.urls import path

from . import views

app_name = "incidents"

urlpatterns = [
    path("", views.incidents, name="list"),
    path("<int:tag>", views.incidents, name="list"),
    path("view/<int:pk>", views.view, name="view"),
    path("resolve/<int:pk>", views.resolve, name="resolve"),
    path("remove/<int:pk>", views.remove, name="remove"),
    path("report/<int:frame>", views.report, name="report"),
    path("report/<int:frame>/<int:tag>", views.report, name="report"),
    #    path('path/', views.view, name='name'),
]

logging_system/locations/urls.py
from django.urls import path

from . import views

app_name = "locations"

urlpatterns = [
    path("", views.locations, name="list"),
    path("add/", views.add, name="add"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("remove/<int:pk>", views.remove, name="remove"),
]

logging_system/logs/urls.py
from django.urls import path

from . import views

app_name = "logs"

urlpatterns = [
    path("", views.logs, name="list"),
    path("<int:label>", views.logs, name="list"),
    path("export", views.export, name="export"),
    path("export/<int:pk>", views.export, name="export"),
]

logging_system/systems/urls.py
from django.urls import path

from . import views

app_name = "systems"

urlpatterns = [
    path("", views.systems, name="list"),
    path("location/<int:location>", views.systems, name="location"),
    path("type/<int:system_type>", views.systems, name="list"),
    path("view/<int:pk>", views.system, name="view"),
    path("logs/<int:pk>", views.logs, name="logs"),
    path("logs/<int:pk>/<int:label>", views.logs, name="logs"),
    path("incidents/<int:pk>", views.incidents, name="incidents"),
    path("incidents/<int:pk>/<int:tag>", views.tag_incidents, name="tag"),
    path("add/", views.add, name="add"),
    path("discover/", views.discover, name="discover"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("remove/<int:pk>", views.remove, name="remove"),
    path("export", views.export_to_csv, name="export"),
    path("export/<int:system_type>", views.export_to_csv, name="export"),
    path("report", views.report, name="report"),
    path("report/<int:system_type>", views.report, name="report"),
]

logging_system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("logging_system.home.urls")),
    path("settings/", include("logging_system.config.urls")),
    path("logs/", include("logging_system.logs.urls")),
    path("systems/", include("logging_system.systems.urls")),
    path("incidents/", include("logging_system.incidents.urls")),
    path("locations/", include("logging_system.locations.urls")),
    path("audit_log/", include("logging_system.audit_log.urls")),
    # path('incidents/', include('incidents.urls')),
]

logging_system/systems/models.py
from django.db import models

from logging_system.locations.models import Location

# Create your models here.
BOOL_CHOICES = [(True, "Yes"), (False, "No")]
SYSTEM_TYPE_CHOICES = [
    (0, "Device"),
    (1, "Computer"),
    (2, "Server"),
    (3, "NAS"),
    (4, "Mobile Phone"),
    (5, "Network Device"),
    (6, "Router"),
    (7, "Switch"),
    (8, "Access Point"),
    (9, "IoT"),
    (10, "NVR"),
    (11, "CCTV"),
    (100, "Service"),
    (101, "Virtual Machine"),
    (102, "Container"),
    (103, "Web Application"),
    (104, "Dataabse"),
    (105, "Backend"),
]


class System(models.Model):
    name = models.CharField(max_length=50)
    ip = models.CharField(max_length=50)
    system_type = models.IntegerField(choices=SYSTEM_TYPE_CHOICES, default=0)
    port = models.CharField(max_length=50, null=True, blank=True)
    to_ping = models.BooleanField(choices=BOOL_CHOICES, default=True)
    last_ping = models.CharField(max_length=50, null=True)
    last_log = models.CharField(max_length=50)
    d_count = models.IntegerField(default=0)
    email_notify = models.BooleanField(choices=BOOL_CHOICES, default=False)
    graph = None
    location = models.ForeignKey(
        Location, on_delete=models.SET_NULL, null=True, blank=True
    )
    service_type = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=50, null=True, blank=True)
    notes = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.name


class Ping(models.Model):
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    system = models.ForeignKey(System, on_delete=models.CASCADE)
    ping = models.IntegerField(null=True)

logging_system/audit_log/views.py
from datetime import timedelta

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone

from logging_system.config.models import Settings
from logging_system.functions import pagination

from .models import AuditLog


# Create your views here.
@staff_member_required(login_url="/accounts/login/")
def logs(request, user=None):
    audit_logs = None
    q = request.GET.get("search", "")
    if user is not None:
        # Fix to display system audit logs
        if user == 0:
            user = None
        if q:
            audit_logs = AuditLog.objects.filter(
                Q(message__icontains=q) | Q(user__username__icontains=q), user=user
            ).order_by("-id")
        else:
            audit_logs = AuditLog.objects.filter(user=user).order_by("-id")
    else:
        if q:
            audit_logs = AuditLog.objects.filter(
                Q(message__icontains=q) | Q(user__username__icontains=q)
            ).order_by("-id")
        else:
            audit_logs = AuditLog.objects.order_by("-id")
    page = pagination(audit_logs, request.GET.get("page"))
    users = User.objects.all()
    data = {"audit_logs": page, "users": users}
    return render(request, "audit_log/list.html", data)


@staff_member_required(login_url="/accounts/login/")
def report(request, frame=0, user=None):
    AuditLog.objects.create(
        user=request.user, message=f"User {request.user} created audit logs report."
    )

    start = (
        timezone.now() - timedelta(weeks=9999)
        if frame == 0
        else timezone.now() - timedelta(days=30)
        if frame == 1
        else timezone.now() - timedelta(days=7)
    )

    audit_log = (
        AuditLog.objects.filter(datetime__gte=start, user__isnull=True)
        .order_by("id")
        .order_by("-id")[:5000]
        if user == 0
        else AuditLog.objects.filter(datetime__gte=start).order_by("-id")[:5000]
        if user is None
        else AuditLog.objects.filter(datetime__gte=start, user=user)
        .order_by("id")
        .order_by("-id")[:5000]
    )

    current_date = timezone.now()
    return render(
        request,
        "report/audit_log.html",
        {
            "date": current_date,
            "start": start,
            "audit_logs": audit_log,
            "user": request.user,
        },
    )

logging_system/config/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect, render

from logging_system.audit_log.models import AuditLog

from .forms import SettingsPage
from .models import Settings


# Create your views here.
@staff_member_required(login_url="/accounts/login/")
def settings(request):
    settings = Settings.load()
    form = SettingsPage(request.POST or None, instance=settings)
    if form.is_valid():
        form.save()
        AuditLog.objects.create(
            user=request.user, message=f"User {request.user} updated settings."
        )
        messages.success(request, "Settings updated successfully")
        return redirect("home")
    else:
        return render(request, "misc/settings.html", {"form": form})


@staff_member_required(login_url="/accounts/login/")
def reset(request):
    settings = Settings.load()
    settings.delete()

    AuditLog.objects.create(
        user=request.user,
        message=f"User {request.user} restored default configuration.",
    )
    messages.success(request, "Configuration restored")
    return redirect("config:settings")


@staff_member_required(login_url="/accounts/login/")
def reset_ml(request):
    settings = Settings.load()

    settings.s1_vectorizer = 1
    settings.s1_vectorizer_parameters = None
    settings.s1_clusterer = 1
    settings.s1_clusterer_parameters = None
    settings.s2_vectorizer = 0
    settings.s2_vectorizer_parameters = None
    settings.s2_clusterer = 3
    settings.s2_clusterer_parameters = None
    settings.on_model_change_reset = False
    settings.ml_anomaly_cluster = 0
    settings.ml_train = 2000
    settings.ml_train_interval = 3
    settings.ml_cluster = 10000
    settings.ml_cluster_interval = 3

    settings.save()
    AuditLog.objects.create(
        user=request.user,
        message=f"User {request.user} restored default ml configuration.",
    )
    messages.success(request, "ML configuration restored")
    return redirect("config:settings")

logging_system/devices/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from website.functions import get_ping_graph
from .models import Device, Log
from config.models import Settings
from .forms import DeviceForm
# Create your views here.

def devices(request):
    if request.user.is_authenticated:
        devices = Device.objects.all().order_by("id")

        # update device last_log
        for device in devices:
            device.graph = get_ping_graph(device.ip)
            last_log = Log.objects.filter(host= device.ip).last()
            if last_log is not None:
                device.last_log = last_log.datetime
                device.save()

        paginator = Paginator(devices, 10)
        page_number = request.GET.get("page")
        page_devices = paginator.get_page(page_number)
        
        return render(request, 'devices.html', {'devices': page_devices})
    else:
        return redirect('home')

def logs(request, pk):
    if request.user.is_authenticated:

        host = Device.objects.get(id=pk)

        label = request.GET.get('label')
        if label is not None:
            logs = Log.objects.filter(host= host.ip, label=label)
        else:
            logs = Log.objects.filter(host= host.ip)
   
        sort_by = request.GET.get('sort')
        if sort_by in ['datetime', 'host', 'program', 'message']:
            logs = logs.order_by(sort_by)
        else:
            logs = logs.order_by('-id')
            
        items_per_page = Settings.load().items_per_page
        paginator = Paginator(logs, items_per_page)
        page_number = request.GET.get("page")
        page_logs = paginator.get_page(page_number)

        return render(request, 'device_logs.html', {'host': host, 'logs': page_logs, 'label': label, 'sort': sort_by,})
        pass
    else:
        return redirect('home')

def add(request):
    if request.user.is_authenticated:
        form = DeviceForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                add_record = form.save()
                messages.success(request, "Device added successfully")
                return redirect('devices:list')
        else:
            return render(request, 'add_device.html', {'form': form})
        return render(request, 'add_device.html', {'form': form})
    else:
        return redirect('home')

def edit(request, pk):
    if request.user.is_authenticated:
        update_it = Device.objects.get(id=pk)
        form = DeviceForm(request.POST or None, instance=update_it)
        if form.is_valid():
            form.save()
            messages.success(request, "Device updated successfully")
            return redirect('devices:list')
        else:
            return render(request, 'edit_device.html', {'form': form})
    else:
        return redirect('home')

def remove(request, pk):
    if request.user.is_authenticated:
        delete_it = Device.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, "Device removed successfully")
        return redirect('devices:list')
    else:
        return redirect('home')

# validated function

# def function(request):
#     if request.user.is_authenticated:
#         pass
#     else:
#         return redirect('home')

logging_system/incidents/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone

from logging_system.audit_log.models import AuditLog
from logging_system.functions import pagination
from logging_system.systems.models import System

from .forms import CommentForm
from .models import Comment, Incident

# Create your views here.


@login_required
def incidents(request, tag=None, system=None):
    incidents = None
    q = request.GET.get("search", "")
    if tag is not None:
        if q:
            incidents = Incident.objects.filter(
                Q(system__name__icontains=q)
                | Q(ip__icontains=q)
                | Q(title__icontains=q)
                | Q(message__icontains=q),
                tag=tag,
            ).order_by("-id")
        else:
            incidents = Incident.objects.filter(tag=tag).order_by("-id")
    else:
        if q:
            incidents = Incident.objects.filter(
                Q(system__name__icontains=q)
                | Q(ip__icontains=q)
                | Q(title__icontains=q)
                | Q(message__icontains=q)
                | Q(tag__icontains=q)
            ).order_by("-id")
        else:
            incidents = Incident.objects.order_by("-id")

    page = pagination(incidents, request.GET.get("page"))
    systems = System.objects.filter(
        id__in=Incident.objects.values_list("system", flat=True).distinct()
    )
    return render(
        request, "incident/list.html", {"incidents": page, "systems": systems}
    )


@login_required
def view(request, pk):
    incident = None
    try:
        incident = Incident.objects.get(id=pk)
    except Incident.DoesNotExist:
        return redirect("incidents:list")

    comments = Comment.objects.filter(incident=incident)
    form = CommentForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.incident = incident
            comment.save()
            AuditLog.objects.create(
                user=request.user,
                message=f"User {request.user} commented on incident '{incident}': {comment}",
            )
            return redirect("incidents:view", incident.id)
        else:
            form = CommentForm()
    incident = Incident.objects.get(id=pk)
    comments = Comment.objects.filter(incident=incident)

    return render(
        request,
        "incident/view.html",
        {"incident": incident, "comments": comments, "form": form},
    )


@login_required
def remove(request, pk):
    delete_it = Incident.objects.get(id=pk)
    AuditLog.objects.create(
        user=request.user,
        message=f"User {request.user} removed incident {delete_it} successfully.",
    )
    delete_it.delete()
    messages.success(request, "Incident removed successfully")
    return redirect(request.META.get("HTTP_REFERER", "incidents:list"))


@login_required
def resolve(request, pk):
    incident = Incident.objects.get(id=pk)
    AuditLog.objects.create(
        user=request.user, message=f"User {request.user} resolved incident {incident}."
    )
    incident.user = request.user
    incident.save()
    messages.success(request, "Incident resolved successfully")
    return redirect(request.META.get("HTTP_REFERER", "incidents:list"))


@login_required
def report(request, frame=0, tag=None):
    AuditLog.objects.create(
        user=request.user, message=f"User {request.user} created incidents report."
    )

    start = (
        timezone.now() - timedelta(weeks=9999)
        if frame == 0
        else timezone.now() - timedelta(days=30)
        if frame == 1
        else timezone.now() - timedelta(days=7)
    )

    incidents = (
        Incident.objects.filter(date__gte=start)[:5000]
        if tag is None
        else Incident.objects.filter(date__gte=start, tag=tag).order_by("id")[:5000]
    )

    current_date = timezone.now()
    return render(
        request,
        "report/incident.html",
        {
            "date": current_date,
            "start": start,
            "user": request.user,
            "incidents": incidents,
        },
    )

logging_system/templates/system/add.html
{% extends 'elements/base.html' %} {% block content %}
<div class="col-md-6 offset-md-3">
    <form method="POST" action="{% url 'systems:add' %}">
        {% csrf_token %} {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Your form has Errors</strong>
            {% for field in form %} 
            {% if field.errors %} 
            {{ field.errors }} 
            {% endif %} {% endfor %}
            <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
                ></button>
        </div>
        {% endif %} 
        <br />
        <h1>
            Add system
        </h1>
        <br />
        <div class="card">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="form-group">
                        {{ form.name.label_tag }}
                        {{ form.name }}
                        <div class="row">
                            <div class="col">
                                IP Address:
                                {{ form.ip }}
                            </div>
                            <div class="col">
                                {{ form.system_type.label_tag }}
                                {{ form.system_type }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                Ping:
                                {{ form.to_ping }}
                            </div>
                            <div class="col">
                                {{ form.email_notify.label_tag }}
                                {{ form.email_notify }}
                            </div>
                        </div>
                        {{ form.port.label_tag }}
                        {{ form.port }}
                        {{ form.model.label_tag }}
                        {{ form.model }}
                        <div class="row">
                            <div class="col">
                                {{ form.location.label_tag }}
                                {{ form.location }}
                            </div>
                            <div class="col ">
                                <br/>
                                <a href="{% url 'locations:add' %}" class="btn btn-dark"> Add Location </a>
                            </div>
                        </div>
                        {{ form.notes.label_tag }}
                        {{ form.notes }}
                        <br />
                    </div>
                </li>
            </ul>
        </div>
        <br />
        <button type="submit" class="btn btn-dark"> Save </button>
        <a href="{% url 'systems:list' %}" class="btn btn-secondary"> Back </a>
    </form>
</div>
<br />
{% endblock %}

logging_system/templates/system/discover.html
{% extends 'elements/base.html' %} {% block content %}
<div class="col-md-6 offset-md-3">
    <form method="POST" action="{% url 'systems:discover' %}">
        {% csrf_token %} {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Your form has Errors</strong>
            {% for field in form %} 
            {% if field.errors %} 
            {{ field.errors }} 
            {% endif %} {% endfor %}
            <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
                ></button>
        </div>
        {% endif %} 
        <br />
        <h1>
            Discover systems
        </h1>
        <br />
        <div class="card">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="form-group">
                        IP Address Range:
                        {{ form.ip_range }}
                        System Type:
                        {{ form.system_type }}
                        {{ form.prefix.label_tag }}
                        {{ form.prefix }}
                    </div>
                </li>
            </ul>
        </div>
        <br />
        <button type="submit" class="btn btn-dark"> Discover systems </button>
        <a href="{% url 'systems:list' %}" class="btn btn-secondary"> Back </a>
    </form>
</div>
<br />
{% endblock %}

logging_system/templates/system/list.html
{% extends 'elements/base.html' %} {% block content %}
<div class="col-md-12">
    <div class="d-flex justify-content-between">
        <div class="input-group mb-3">
            <a class="btn btn-secondary" href="{{ request.META.HTTP_REFERER|default:'/' }}">&laquo; Back</a>
            <a class="btn btn-outline-dark disabled" > Systems </a>
            <a class="btn btn-dark" href="{% url 'systems:add' %}"> Add System </a>
            <a class="btn btn-dark" href="{% url 'systems:discover' %}"> System Discovery </a>
            <a class="btn btn-dark" href="{% url 'locations:list' %}"> Manage Locations </a>
            <a
                class="btn btn-dark text-white dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >
                Export to CSV
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'systems:export' %}">All systems</a></li>
                <li><a class="dropdown-item" href="{% url 'systems:export' 0 %}"> Devices </a></li>
                <li><a class="dropdown-item" href="{% url 'systems:export' 1 %}"> Services </a></li>
            </ul>
            <a
                class="btn btn-dark text-white dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >
                Export to PDF
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'systems:report' %}">All systems</a></li>
                <li><a class="dropdown-item" href="{% url 'systems:report' 0 %}"> Devices </a></li>
                <li><a class="dropdown-item" href="{% url 'systems:report' 1 %}"> Services </a></li>
            </ul>
        </div>
        <form method="get" class="align-self-center">
            <div class="input-group">
                <input class="form-control" type="text" name="search" value="{{ q }}" placeholder="Your query">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </form>
    </div>
    <div class="accordion" id="accordionServices">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <div class="accordion-button collapsed">
                    <div class="container text-start">
                        <div class="row">
                            <div class="col-1">ID:</div>
                            <div class="col-2">Name:</div>
                            <div class="col-2">IP Address:</div>
                            <div class="col-2">
                                <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false"
                                    >
                                    System Type:
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'systems:list' %}">All</a></li>
                                    <li><a class="dropdown-item" href="{% url 'systems:list' 0 %}"> Device </a></li>
                                    <li><a class="dropdown-item" href="{% url 'systems:list' 1 %}"> Service </a></li>
                                </ul>
                            </div>
                            <div class="col-1">Status:</div>
                            <div class="col-2">Packet Loss:</div>
                            <div class="col-2">
                                <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false"
                                    >
                                    Location
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'systems:list' %}">All</a></li>
                                    {% if locations %}
                                    {% for location in locations %}
                                        {% if location.id %}
                                        <li><a class="dropdown-item" href="{% url 'systems:location' location.id %}"> {{ location }} </a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </h2>
        </div>
        <div style="max-height: 70vh; overflow-y: auto;">
        {% for obj in systems %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ obj.id }}">
                    <button
                        class="accordion-button collapsed"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapse{{ obj.id }}"
                        aria-expanded="false"
                        >
                        <div class="container text-start">
                            <div class="row">
                                <div class="col-1">{{ obj.id }}</div>
                                <div class="col-2">{{ obj.name }}</div>
                                <div class="col-2">{{ obj.ip }}</div>
                                <div class="col-2">{{ obj.get_system_type_display  }}</div>
                                {% if obj.last_ping %}
                                <div class="col-1 text-success">{{ obj.last_ping }}</div>
                                {% else %}
                                <div class="col-1 text-danger">Down</div>
                                {% endif %}
                                {% if obj.loss %}
                                <div class="col-2 text-danger">{{ obj.loss }}&percnt;</div>
                                {% else %}
                                <div class="col-2 text-success">{{ obj.loss }}&percnt;</div>
                                {% endif %}
                                <div class="col-2">{{ obj.location }}</div>
                            </div>
                        </div>
                    </button>
                </h2>
                <div
                    id="collapse{{ obj.id }}"
                    class="accordion-collapse collapse"
                    data-bs-parent="#accordionServices"
                    >
                    <div class="accordion-body">
                        <div class="btn-group" role="group">
                            {% if obj.port %}
                            <a href="http://{{obj.ip}}:{{obj.port}}" class="btn btn-dark">
                            Connect
                            </a>
                            {% endif %} 
                            <a href="{% url 'systems:view' obj.id %}" class="btn btn-dark">
                            View
                            </a>
                            {% if obj.last_log %}
                            <a href="{% url 'systems:logs' obj.id %}" class="btn btn-secondary">
                            Logs
                            </a>
                            <a href="{% url 'systems:incidents' obj.id %}" class="btn btn-secondary">
                            Incidents
                            </a>
                            {% endif %}
                            <a href="{% url 'systems:edit' obj.id %}" class="btn btn-secondary">
                            Edit
                            </a>
                            <a href="{% url 'systems:remove' obj.id %}" class="btn btn-danger"
                                >Remove</a
                                >
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br />
    {% include 'elements/pagination.html' with objs=systems %}
</div>
{% endblock %}